input_camera_topic: "/zed2/zed_node/left_raw/image_raw_color"
input_bounding_boxes_topic: "/zed2/zed2/topic_bbox_zed2d"
input_lidar_topic: "/lidar_cones"
output_topic: "/fusion_cones"

visual_debug: true
